version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerFile.backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./api:/app   # optional: hot reload
      - ./model:/app/model
  frontend:
    build:
      context: .
      dockerfile: dockerFile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./mood-music-frontend:/app  # optional: hot reload
