FROM python:3.10-slim

WORKDIR /app

# Install system dependencies for OpenCV
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Install fastapi-cli
RUN pip install fastapi[standard]

COPY model ./model

EXPOSE 8000

# Start FastAPI with live reload (same as your local command)
CMD ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "8000"]
